import * as fs from 'fs';
import * as path from 'path';
import { Component } from 'projen';
import { workflows, GithubWorkflow } from 'projen/lib/github';
import { NodeProject } from 'projen/lib/javascript';
import { copyFiles } from '../utils/copyFiles';

const filename = 'createDependabotIssue.ts';

/**
 * Create dependabot security notification workflow for the project.
 * This creates an issue if there is a dependabot security finding from Github.
 */
export class DependabotSecurityNotificationWorkflow extends Component {

  constructor(project: NodeProject) {
    super(project);

    // Copying script files for this workflow
    this.copyFilesOver();

    const workflow: GithubWorkflow = project.github!.addWorkflow('Dependabot-Security-Notifications');

    const runEveryFiveMins = '*/5 * * * *';
    const trigger: workflows.Triggers = {
      schedule: [{
        cron: runEveryFiveMins,
      }],
    };

    const runsOn = ['ubuntu-latest'];
    const pathToScript = 'scripts';
    const job: workflows.Job = {
      name: 'dependabot-security-notification',
      runsOn: runsOn,
      permissions: {
        securityEvents: workflows.JobPermission.READ,
        issues: workflows.JobPermission.WRITE,
      },
      steps: [
        {
          name: 'Checkout',
          uses: 'actions/checkout@v3',
        },
        {
          name: 'Install and Build',
          run: `yarn install --frozen-lockfile && yarn build && yarn test && cd ${pathToScript}`,
        },
        {
          name: 'Run Script',
          uses: `./${pathToScript}/${filename}`,
          env: {
            GITHUB_TOKEN: '${{ secrets.PROJEN_GITHUB_TOKEN }}',
            REPO_ROOT: '${{ github.workspace }}',
            REPO_NAME: '${{ github.repository }}',
            OWNER_NAME: '${{ github.repository_owner }}',
          },
        },
      ],
    };


    workflow.on(trigger);
    workflow.addJob('dependabot_security_notification', job);
  }

  copyFilesOver() {
    const sourceDir = path.join(__dirname, '../components/scripts');
    const destinationDir = path.join(__dirname, '../../scripts');

    copyFiles(sourceDir, destinationDir);
    addProjenGuidance(`${destinationDir}/${filename}`);
  }
}

function addProjenGuidance(filePath: string) {
  const guidance = '// ~~ Generated by projen. To modify, edit file in cdk8s-projen-common at src/components/scripts and run "npx projen".\n';

  let file = fs.readFileSync(filePath).toString().split('\n');
  file.splice(0, 0, guidance);
  const newFile = file.join('\n');

  fs.writeFileSync(filePath, newFile);
}