import * as src from './src';

const project = new src.Cdk8sTeamJsiiProject({
  name: '@cdk8s/projen-common',
  description: 'Common projen configuration shared between cdk8s-team org projects.',
  peerDeps: ['projen'],
  deps: ['codemaker', '@octokit/rest', '@octokit/types'],
  bundledDeps: ['codemaker', '@octokit/rest', '@octokit/types'],
  projenrcTs: true,
  defaultReleaseBranch: 'main',
  pypi: false,
  maven: false,
  nuget: false,
  golang: false,
});

// copy the components to lib because it contains
// resources required at runtime. should probably do done via tsconfig.json
// but since it is generated by jsii I don't think thats configurable.
project.preCompileTask.exec('mkdir -p lib && cp -r ./src/components ./lib');

project.synth();
